### ISSUE TITLE
CashMod Menu

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD151#25]
Cashmod has 3 menus basically. We can loose two of them since we collapsible ACP tabs. 3 menus is just way redundant to be quite frank.

**Comment by vendethiel** [comment]
let's just remove the separators?

**Comment by MWE001** [comment]
and by doing that we ill essentially only have the sidebar nav menu correct? I believe this is what we are trying to get luca to do as well. I just think for ease of use and appearance it will be much nicer.

So We would need to get rid of the menu or sidebar option in cash config, get rid of the cashmod header navigation bar and default it to be set to sidebar nav default on install.

This isn't a must do right now, just something I been thinking about as well since we are trying to get it done at icy as well.

**Comment by vendethiel** [comment]
> and by doing that we ill essentially only have the sidebar nav menu correct? I believe this is what we are trying to get luca to do as well. I just think for ease of use and appearance it will be much nicer.

I mean, I can do it. I just want Luca to approve... That's the hardest part working on IP – MG's free time is **really** stretched. So on some occasions, my work was never integrated after several years. That's why I don't spend as much time working on IP: I wait for MG's input everytime. So I'm sure I'm not wasting time. Like https://github.com/MightyGorgon/icy_phoenix/pull/5 : 2 years without an answer :(.

**Comment by MWE001** [comment]
Yeah that is very hard. I understand. it makes it hard to have any get up and go. I badly want to make this happen. I can make it work, but there is a difference in making it work and doing it properly. I simply refuse to try it if I know I can't do it right. I might use it on my own personal site but not a downloadable package for public.

I can certainly understand your not spending much time developing. Two years is nuts with no answer.

**Comment by vendethiel** [comment]
> Yeah that is very hard. I understand. it makes it hard to have any get up and go. I badly want to make this happen. I can make it work, but there is a difference in making it work and doing it properly.

Building a community is oh-so-hard... One of the thing I'm the worst at.

> Two years is nuts with no answer.

To be fair, we were still discussing on the forum and al. Some of my patches got merged. But this one didn't get an answer. Oh well.

**Comment by MWE001** [comment]
Yep. Win some loose some. If I can pull it off here, it's gonna happen. 3 menus is just over exaggerated really bad and a waste of server resources and user time. One and done is how it should be. The album menu, that is manageable two ways but cash mod menu, no. It's got to change.

**Comment by vendethiel** [comment]
You might be interested in https://github.com/MightyGorgon/icy_phoenix_plugins/pull/49/files. Especially the changes on the first file. The rest is specialcased because Icy has(had) a bug when navbar is disabled.

**Comment by vendethiel** [comment]
(btw, if you want to follow my work on AD&R, it's [here](https://github.com/vendethiel/ezarena). I'll port it over when I deem it good enough :D)

**Comment by MWE001** [comment]
Ok cool. Ill have a look.

**Comment by MWE001** [comment]
I am curious if we are on the same page when it comes to the Cash mod menu. Check this out and let me know if we are on the same page or not.

![cashacp](https://cloud.githubusercontent.com/assets/2566493/18890358/5d6588cc-84c6-11e6-8f3d-4810e2ca19d9.jpg)

![cashacp2](https://cloud.githubusercontent.com/assets/2566493/18890364/6566a2c2-84c6-11e6-84bf-89f5ebb263b8.jpg)

![cashacp3](https://cloud.githubusercontent.com/assets/2566493/18890367/6c8fafbc-84c6-11e6-83c0-58d1a74b00ad.jpg)

**Comment by vendethiel** [comment]
I left the option to enable navbar, IIRC. But the admin menu is forced ON.

**Comment by MWE001** [comment]
That's do'able then.

**Comment by vendethiel** [comment]
I tried it before opening the pull request yeah

**Comment by MWE001** [comment]
Ok. Sounds good.

**Comment by vendethiel** [comment]
@MWE001 any update on this? :)

**Comment by MWE001** [comment]
I actually downloaded a IM 151 a few days back and installed it and that is as far as I got. I literally got my hands full here lately. I had to build that Icy site again got it online and got charged to build 3 more sites from scratch. All Bootstraps. One with a custom back end which i know nothing about. I might have to farm that out. Not sure yet.

BUT back to cash mod. If I get a chance today I will take a look and see whats up.

**Comment by MWE001** [comment]
@vendethiel  I think this one is solved and can be closed to. The Integra version the Helter added over at Integra site, the cashmod is working just fine as far as I can tell. I have not really got up under the hood of it like I am know for doing but normal every day test drive has been ok thus far.

**Comment by vendethiel** [comment]
Good
