### ISSUE TITLE
Consolidating Icy

### ISSUE THREAD

**Issue by vendethiel** [IntegraMOD/IntegraMOD151#30]
Hey Ray,

Thanks for uploading this package here. I've really been able to see a great premod in action, and I really wish I knew of it back then.

However, I can't work on both IP and IM (plus my AD&R RPG).
I can however recognize that several IM mods are missing from IP.

I'd be okay with adding them to Icy (under a plugin) so that we have the best of both worlds.

However, I do not know for sure of the missing mods. Since IM has the hacks_list.php page, and IP the credits.php, could you please tell me which mods are missing so I can work on that?

That'd be really amazing I think. Especially since you got the IM theme ported - so you can have what you like of IM with IP's niceties and more modern codebase.

I'd understand if you wished not to do that. But I think it'd be amazing.

Thanks!

(Some mods might "duplicate" each other: Prillian on IM already exists on IP (you can instant-message friends))

**Comment by MWE001** [comment]
Yeah we can come up with a list of mods I'm sure. that shouldn't be an issue at all.

**Comment by MWE001** [comment]
And I don't expect you to try to work on 3 or 4 projects  lol 1 or 2 is to much at times man. Just stop by every now and again if you feel like it and have a look. I don't do to awful bad, but at random times I do need a hand with something.  lol I'm so old I have forgotten more than I ever knew  ;-)

**Comment by vendethiel** [comment]
Let's go.

- [x] Acronym Mod 0.9.4 - CodeMonkeyX
- [ ] Add status to topic 1.0.3 - Acid
- [ ] Admin-Mods List Page 1.1.1 - Woody
- [x] Advanced Links Mod 1.2.2 - stefan2k1 (plugin on IP)
- [ ] Announces Suite 3.0.2 - Ptirhiik
- [ ] Approve Mod 1.0.9 - Aceman
- [x] Auto Group 1.2.1 - Niels
- [x] BBCode Strike 1.0 - R0cKW|LDeR
- [x] BBCode Sup & Sub 1.0.0 - Lunatic 
- [x] Bookmarks 1.1.1a - PhilippK
- [?] Bots MOD 1.0.0 - Adam Marcus
- [x] Cash Mod 2.2.3a - Xore 
- [x] Categories Hierarchy 2.0.4 - Ptirhiik
- [x] ChatSpot 3.02 - Project Dream Views (we have 2 shoutboxes already)
- [x] Complete Banner 1.3.4 - Niels (we have an equivalent one with top/bottom tags)
- [x]  CrackerTracker 5.0.3 - cback
- [ ] Delayed Topics 1.0.0 - themaze75
- [ ] DHTML Calendar Widget 0.9.6 - Mihai Bazon
- [x] DHTML Slide Menu for ACP 1.0.1 - markus_petrux
- [x] [!] Digests 1.2.0 - MarkDHamill (Icy has 1.0.13)
- [x] Disable board message 1.0.0 - Sko22
- [x] Donation MOD 1.0.2 - sandodo (Our donations plugin) 
- [x] [!] Download topics and Posts 1.0.2 - OXPUS (Icy has 1.0.0)

TODO (from IM, not checked on IP yet):
- [ ] Error Mod 0.0.1 - Josh
- [ ] Extended Quote Tag 1.0.0 - Acyd Burn
- [x] eXtreme Styles MOD 2.3.1
- [ ] Faq Manager 1.0.0 - Selven
- [ ] File Attachment Mod 2.3.10 - Acyd Burn
- [x] Fix message_die for multiple errors - markus_petrux
- [ ] Force Topic Read 1.0.2 - aUsTiN
- [ ] Forum Tour 1.0.3 - OXPUS
- [x] Full Album Pack 1.2.3 - MightyGorgon 
- [ ] Fully integrated shoutbox 1.0.10 - Niels
- [ ] Google search BBCode 1.1.1 - wGEric
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 

Note: I didn't add the PCP (Profile Control Panel) mods to the list, because Icy has its own system.

**Comment by vendethiel** [comment]
Just did the maths. That's 47 mods.

Note: by maths, I mean JavaScript:
```
$$('.task-list-item-checkbox:not([checked])').length
> 47
```

**Comment by MWE001** [comment]
Sorry man wife had PC all day I hadn't got to look at nothing or do anything. 

As far as the PCP goes, I never enjoyed having it. You had to have experts on hand to get mods installed. I got ok with it and made a couple mods wok but it was more than I ever wanted to have to do on a daily basis. I hated PCP with a passion. And the CH mod is nice because of what it does, but like PCP it pretty much does away with much of the core code.

**Comment by Phosphorus-M** [comment]
Yep, I tried to install the mods CH and PCP in a forum Phpbb2 with IM but nothing good came out of it, I finally finished installing alternative mods which served the function of PCP and CH Mod, IM portal it's more important that CH and PCP mods for me.

**Comment by MWE001** [comment]
Yeah totally not taking anything away from Ptirhiik. He did an awesome job on his mods and what they were capable of doing but it is just to much .... for my taste. I like to use IMPortal and install what I wanted and use a simple sub forum type of mod instead of CH. And somewhere, I do have simple sub forums made specifically for phpBB 2.0.24 from phpBB refugees.

**Comment by vendethiel** [comment]
Okay, then I guess we're settled? You agree with my list of what's missing?

**Comment by MWE001** [comment]
I have not got to compare the hacks list to IP credits yet. I went to bed last night and literally just got on PC a bit ago when I replied that wife had the PC all day  lol So actually, my day is just beginning. The list is looking good so far.

**Comment by vendethiel** [comment]
I think a big part of it is that Integra "inflates" its admin size by having menus with only one option in them. So it looks like it's more featureful. But mostly IP has equivalents, they've just been sorted out in logical pieces (because all the mods have been molded together. They feel more independent on Integra).

@Phosphorus-M glad to see you joining the fun ;-).

It won't be an easy road to install those mods. And I'll need to work a lot on the plugins system... Sounds like fun though ;-)

**Comment by vendethiel** [comment]
> Yeah totally not taking anything away from Ptirhiik. He did an awesome job on his mods and what they were capable of doing but it is just to much .... for my taste.

I was talking with MG earlier and we both agree that PCP is **faaaar too complex** anyway. I mean – you even need the *pcp wizard* mod to use it at all. Mess up once, board broken...

**Comment by MWE001** [comment]
Yeah exactly right. One mistake and hope you got a backup handy.

When I mentioned Ptirhiik I was replying to @Phosphorus-M post about CH and PCP. 

And yeah IM Admin panel is way inflated. I kinda like it better but not. I will admit I had a very hard time finding stuff in Icy ACP. The CMS was pretty easy to figure out but simple issues in the ACP I had to take the time to look until I was blue in the face. So I guess it's 6 in one and a half dozen in the other. I like slim line but I hate hard to find. I am your typical Lazy internet user. I learned long ago working on sites what is easy for me, might not be for another user. And if you don;t cater to lazy people, off they go. That is why everyo9ne is  hooke don facebook now. its a one stop shop. They canbe lazy and never leave. Thus the term, lazy internet users. =) I think the biggest thing is when working on a public project is to NOT make it personal flavors. That is why I just closed a couple issues here after I thought about it for a while. Leave the mods as is, if they work. HOWEVER, some are just ridiculous, for example, cash mod menus.... Nuts! There is a point in time where edits must be done.

**Comment by MWE001** [comment]
As far as admin panel goes, I would love to see it slim lined in a way that does not hinder user frienliness (if thats a word =) )

**Comment by vendethiel** [comment]
I'll admit it's really hard to get used to new ACPs hahaha. I have around 10 installed phpBB2 premods, and I keep switching between games, so I'm starting to correctly remember...

**Comment by MWE001** [comment]
Of all the mods that would push Icy over the top for me immediately is Subscriptions for a few reasons. Not that anyone uses forums anymore but if you have content people want, they will come. Look up BBQ Brethren, Killthecan.org, and many others. 

And the ability to set what group can use images in signatures and how many chars each group can use in sigs. 

Those two mods alone would make my day!

And yeah different CMS ACP panels are hard to get used to  lol. I'm good with Icy now. At first it sucked for me but now i pretty much fly right through it. I'm still learning it but it works for me.

**Comment by vendethiel** [comment]
You mean paid subscriptions?

**Comment by MWE001** [comment]
yeah. Paid subscriptions. Where  they could be added to a group and get extra benefits of being a member such as extra access to hidden forums, etc etc

And sorry so slow on the reply. Had to run up to the school to get my boy. They evacuated the school due to bomb threat.

**Comment by vendethiel** [comment]
Gosh. Hopefully nothing bad happened... People here (france) are also very careful about that.

I'll see if we can add paid subs to the gaypal mod. Not sure how paypal works.

**Comment by Phosphorus-M** [comment]
My mother tongue is spanish, I will can translate the language files.
Some time ago I had a similar project and the ACP was filled with menus, I thought of replacing the "Index Management" categories template and eliminating some lateral links.

**Comment by vendethiel** [comment]
Which one language files?

**Comment by MWE001** [comment]
Actually, speaking of ACP, I had a thought some time back before life got in the way, of making a list of ACP options in Integramod and figuring out how to combine some stuff like the Integra team did back in the day when they came up with the configuration +. I think many things can be slim lined. All in good time.

**Comment by Phosphorus-M** [comment]
English to Spanish, the general files.

**Comment by MWE001** [comment]
Here are the ones that were made for Integra 1.4.1. I am not sure how accurate most of it would be for Integramod 150

![screenshot_44](https://cloud.githubusercontent.com/assets/2566493/18568638/bdbfcab4-7b63-11e6-8cb4-85a81312ef8c.jpg)

**Comment by MWE001** [comment]
I can't translate or do mods for Icy. We all know my coding is not the finest. I can do a bug or two here and there. All I can do is attempt some templates.

I got one being finished up hopefully today and gonna start another one in a day or two. Depends on life and what it wants me to do. 

I will do what I can to help though. I just got to split my time between here and there.

**Comment by IntegraMOD** [comment]
I dont think github has the latest version. Its been quite awhile since I messed with this project. The working copy of the latest one is here http://www.forumimages.us/IM150. We patched up most mods and hundreds of depreciated functions and stopped at fixing the dl mod. You guys have been busy so youve probably already surpassed what Mike and I did but if you want the latest version we did, let me know. I never got the hang of git so I stuck to subversion

**Comment by MWE001** [comment]
That would be great actually for comparison reasons. I got a couple issues that I am having problems with that you guys might have got fixed. 

And did Mike give up on Stargate? I went to his git and its been a couple to many years since any updates.

**Comment by MWE001** [comment]
Oh ok @IntegraMOD I wasn't sure what was happening. I went to go there one day to look for something and poof! I was like well, shoot. I figured it had lived it's life. I'm not sure if I am needing full access or what. I think I am just having something to do and grasping at straws really. I don't get out much, live on opioids due to my back being so bad and rarely to never leave home except when needed. So this is what I do to keep my brain moving forward or the opioids will take away my will to live. 

So code it is! lol I'm not worth a crap at it but it is keeping me going day after day. Sometimes I swing and miss, other days I can get a grand slam. It just depends.

**Comment by vendethiel** [comment]
@IntegraMOD nice! I think it'd be interesting to have your working. we can use git or any other diff tool to see how we can merge those.

It also seems like you have language packs, so that's really good :).

I don't have an account over at integramod, so even if you removed the redirect, I wouldn't be able to participate since registrations are closed. (I do wish I discovered it sooner, but oh well)

Just to make my stance clear: I will fix bugs on IM (or security issues, or critical performance issues), but I won't be evolving it. That's why I'm planning to add mods to Icy to make it a viable alternative to Integra.

However I still think Integra should be present as a solution for people that want it - that's why I plan to "maintain" it.

My RPG will probably be available for both. But it'll probably be much easier to make it work on Integra because the codebase is so similar to phpBB2.

@phosphorus-m I might deprecate EzArena and migrate the AD&R to Integra, even if it's just the time to finish the changes. The final plan will stay the same, make it work on IP. But for now deprecating EzArena means I'll only need to support 2 premods, not 3...

**Comment by MWE001** [comment]
@vendethiel I wouldn't be quick to deprecate anything just yet.  Remember that IntegraMOD has PCP installed. I am 100% positive if you have never worked with it before, you will not want to try to integrate. It's your project though. Just giving friendly advice. I have tried a few times with IntegraMOD and AD&R and it didn't go so well. I wouldn't fall for the same thing that I did and look at the hacks list and say Oh look at that! It worked why not this. Helterskelter and the team basically rebuilt a lot of them mods to make them work with Integra. it is a great CMS to work with and use but the PCP, well it kind of puts the stomps on many plans.

If he removed the redirect you would be able to register I am pretty sure. I am sure he just closed it since it was basically going to be a archive of sorts. The problem with reopening it is, the site is running a version of IntegraMOD running phpBB3. Since that is NOT the project being worked on here, that makes it rough to run a site like that. It should be ran off of the package exactly as it is made available for download. Nothing more, nothing less. And cost too. I'm not going to ask Helterskelter to reopen something and run the server and me not foot the bill. Truth be known, I don't work and am broker than a 3 legged dog. Literally. 

As far as his copy of IntegraMOD him and Mike worked on, yeah, I would love to have it for comparison to what we have here now that we have worked on it for a few days. I'm curious to see what differences there are. May be they fixed a few things that I have been trying to figure out for a couple days now.

And Evolving will happen or it won't. As stated in my earlier response, the only reason I do this is to keep me active and using my brain. I take so many meds every day that if I quit, I am done for. I refuse to loose and this just helps me live life day to day. When you get to be an old fogie like me and run down and beat up, you'll understand. lol It is not a do or die project for me, I just hate to see it go by the way side. I enjoy getting to work on it. If I can make upgrades, cool. if not, I'm not going to cry about it. =) My wife said Facebook wins we loose and to just give it up. NOOOO! 

I appreciate any little or major thing you wish to do. I really do. I have enjoyed working on this the last couple days, BUT I still got work to do for Icy as well. back to it I go. I can squeeze in another hour or so before bed.

Think about that Deprecating ADR thing man. PCP sucks.

**Comment by MWE001** [comment]
BUT...... if you can pull that off , AD&R with IM, you would officially be the man like Dwho  (Foundit) was back when he made MPS Mod work with Icy. ;-)

**Comment by vendethiel** [comment]
I will not be integrating PCP. It's just a bad idea. As for AD&R - if I said I'll integrate it into Integra, I'll do it. I've been programming in PHP for around 10 years, and I think up until now I've put my money where my mouth is - fixing what I said I would.

I don't mean to "deprecate" Integra. As I said, I plan to make sure it's there as a viable option. I understand very well what you're feeling towards it — it's the same with me and Icy, really.

Please make it evolve! It'd be amazing. I was just talking about my priorities. The fact **I** won't be evolving it doesn't mean no one will. I'll be available to give a hand to people who try.

**Comment by MWE001** [comment]
Sounds good man. I'm in.

**Comment by vendethiel** [comment]
> You fellers have a wonderful day/evening what ever time it is where you are.

10am ;-). Isn't the internet a wonderful thing.

**Comment by vendethiel** [comment]
@IntegraMOD I'm not sure why dload.php is failing on your server. The fix I added was regarding CrackerTracker, not some `$template` misbehavior... I can't reproduce the error locally :(.

**Comment by IntegraMOD** [comment]
integramod.com is back online. I put IM150 in the beta section of downloads. @vendethiel If you register, ill add you to the dev team so youll have access

**Comment by IntegraMOD** [comment]
I think in order for IM to ever be relevant again it needs a few things. #1 is a responsive, bootstrap type template. I started new layout for KISS Portal/IM here http://www.forumimages.us/layout/portal.html  It is just a static example and still needs work but it was just an idea. #2 is better social media integration. Other than that, it just need to function correctly. I wish I had the time and energy to help you guys but real life is busy and IMportal, KISS Portal and IntegraMOD151 and our various templates have totally burned Mike and I out...lol

**Comment by MWE001** [comment]
Hi guys. Net dropped at 3 this morning and not back on. Apparently it takes 5-7 days to get tech support to the house. Catch you all then.

**Comment by vendethiel** [comment]
I registrated.

I agree with @MWE001 that it's a bit weird this one is running phpBB3 when we're maintaining IM150, but it's still good!

Social media integration would be good (I did the Google one for Icy. I'm not starting work for IM but I'll help whoever does!)

I have no ideas about templating stuff, sorry.

Btw, I did burn out once. Take your time! Step back and enjoy the fact several other people like your projects :D

**Comment by IntegraMOD** [comment]
seems like we spent hundreds of all nighters working on Integramod since around 2004 so its unlikely Ill be jumping back in anytime soon..lol The reason the forum is running phpBB3.0.x is that we released IM3 for awhile and the forum is still running it. We decided to drop it because almost all of the mods were never completed by their authors and those that were completed where dropped with no support. Also all the devs at integra left and I was on my own. Mike from phpbbireland help alot but he was neck deep in KISS Portal. It was way too big of a project for just me.

**Comment by vendethiel** [comment]
That sounds about right. (when I said "take your time", I didn't mean I expected you to come back, just for you to enjoy whatever you're doing now).



> Also all the devs at integra left and I was on my own. Mike from phpbbireland help alot but he was neck deep in KISS Portal. It was way too big of a project for just me.

Yeah, I think you did an amazing job considering :-). I'll try to look at the beta package you uploaded during the weekend. Thanks for the "keys"! :)

**Comment by vendethiel** [comment]
It's the opposite for me: Back in the days, I was utterly useless (too young to help or speak english anyway.. lol) so I kind of want to "pay back" the amazing stuff I've done with boards back then now :-).

**Comment by vendethiel** [comment]
@IntegraMOD looked at your package. A lot of it seems to be the replacement between $HTTP_POST_VARS and $_POST (and the likes)

**Comment by MWE001** [comment]
I'm back fellas. My net just mysteriously came back on. I still got tech coming out Wednesday to check everything out. 

> A lot of it seems to be the replacement between $HTTP_POST_VARS and $_POST (and the likes).

I did the same thing with a complete AD&R install once. WOW there was some replacing going on. lol 

Ok sorry about that back to Integra now. I need to catch up after taking a few days off. I'm working oin a icy phoenix install at the moment. I'll jump on Integra in a bit.

**Comment by MWE001** [comment]
> It was way too big of a project for just me.

And all I was able to help do was keep spammers at bay and was on the very rare occasion able to answer a question about pcp but that was rare. I got lucky with some IMPortal 130 edits. I understand a lot more now but it is to little to late. IM was a very big project for any one man to try to do by them selves.

Speaking of IMPortal 130 it has major css issues that render it all but useless. lol. That's another project for another day.

**Comment by MWE001** [comment]
I'm still alive and kicking boys. Life has got the best of me this last week or so. I have not had time to jump in any code what so ever really. Going to try today to do some work.

@vendethiel I am going to install your copy today and give it a try. It is the one that matches the master her on Git correct?

**Comment by vendethiel** [comment]
Yes, you merged the pull request, so it's correct

**Comment by MWE001** [comment]
Ok. Thanks. I got side tracked tonight but have visions for tomorrow.

Ray

**Comment by vendethiel** [comment]
Confirmed we have a merge mod on IP!

I have a few PRs opened over at IP. I'll try to get some plugin work done this week! Not sure I'll be able to implement any mod, but I should get some time to work on the foundations.

**Comment by vendethiel** [comment]
Going to check off " Add status to topic 1.0.3 - Acid" as well, because of Quick Title Edit. Maybe I should move the version IM uses to have a configurable admin row instead.

**Comment by vendethiel** [comment]
I got to write the first IP Plugin! [Here is Announces Suite](https://github.com/vendethiel/icy_phoenix_plugin_announces_suite) – the idea is that you don't need to modify the code anymore. But you still keep all the nice features.

**Comment by MWE001** [comment]
Sounds great man! I can't wait until i can start in again. Every time I attempt to do anything something comes up. My health is failing miserably as well. 

I am going to try as I might to get this 150 installed tonight and going.

**Comment by vendethiel** [comment]
Take care of your health first, that's much harder to fix than a phpBB mod ;).

**Comment by vendethiel** [comment]
I ported as group moderatorz as a plugin as well.

I'm starting to consider some changes could be made to the portal in integraMOD, i like icy's cms better to be honest

**Comment by Phosphorus-M** [comment]
@vendethiel I totally agree with what you say, the portal by Icy Phoenix is the best CMS for Phpbb.

**Comment by vendethiel** [comment]
@Phosphorus-M now that EzArena works well (no bugs I found recently), I'm gonna port AD&R to IntegraMOD (then it's easier for e.g. @winzombie 's avatar mod to be installed).
I'm gonna add mods to Icy as extensions (no code changes needed).

**Comment by MWE001** [comment]
ICY has an awesome CMS, but it is not phpBB anymore in it's own special kind of way. it is very bastardized. Nice, but not phpBB. That is part of the reason Mort gave up on it as well. it was no longer phpBB, it was a personal want version of Luca. It took me a little bit to figure it out but when I did it was a non issue getting around the cms at all. 

The one area I did have an issue with in ICY and would hope it can be avoided on Integra is two separate areas for CMS and another for phpBB stuff. I like the menu in Integra the way it is. All in one area. that is just me and my personal opinion and you know what is said about opinions so I will leave it be at that.

I got some pain meds on board right now for my back and will revisit this thread tomorrow after all meds are out of me to make sure I even made sense to myself. 

take care guys.

**Comment by vendethiel** [comment]
Yeah I'd sure love to be able to put Icy's CMS everywhere :-).

**Comment by vendethiel** [comment]
Gonna move that last comment about the CMS to someplace else.

**Comment by vendethiel** [comment]
Updated the list. The count at the end is 31.

I have not found these mods yet in the phpbb archive:

```
To download:
 Delayed Topics 1.0.0 - themaze75
 DHTML Calendar Widget 0.9.6 - Mihai Bazon
 [!] Digests 1.2.0 - MarkDHamill (Icy has 1.0.13)
 [!] Download topics and Posts 1.0.2 - OXPUS (Icy has 1.0.0)
 [?] Faq Manager 1.0.0 - Selven
 [!] Force Topic Read 1.0.2 - aUsTiN (Icy has 1.0.1)
 Forum Tour 1.0.3 - OXPUS
 [!] Fully integrated shoutbox 1.0.10 - Niels (Icy has 1.0.7)
 Group Extend 0.0.1 - Malicious Rabbit
 Group Extra Emails 1.0.1 - Malicious Rabbit
 [!] Mini Cal 2.0.2 - netclectic (Icy has 1.1.0 – we really need to update)
 MyCookies Manager 1.1.0 - A_Jelly_Doughnut
 No flood control on edit 1.0.0 - Graham
 No Thread stretch 1.3.0 - Thoul
 Optimize Database 1.2.2 - Sko22
 Paypal Group Subscription 1.0.3 - sandodo
 phpBB Database Cleaning 1.1.1 - Florian_DVP
 phpBB Security 1.0.3 - aUsTiN
 Private Message Review 1.0.0 - masterdavid
 Rank images drop down menu 1.0.0 - Antony Bailey
 Ranting system 1.1 - Gentle
 Repeating events MOD v? - Antoon
 [!] Send PM on user registration 1.0.4 - AbelaJohnB (Icy has 1.0.2)
 [!] Statistics Mod 3.0.0 - Acyd Burn (Icy has 2.0.15)
 [!] Tell A Friend 1.3.0 - Hardout (Icy has 1.0.0)
 Text-based visit counter 1.1.1 - Smartor
 You bbcode 1.0.1
 Pseudocron
 Redirect Admin PMs



Seem unnecessary:
 phpBB2 Fast Hack 1.0.0 - dwing
 phpBB Spell v3.1 - ?
 Posting popups 1.3.0 - david63
 Rebuild Search mod 1.0.0 - Guild
 Smilies Upload utility - 1.1.10 - Thoul
 Type Quietly 1.0.1 - Lars Janssen
```
