### ISSUE TITLE
referers block

### ISSUE THREAD

**Issue by IntegraMOD** [IntegraMOD/IntegraMOD151#39]
referrers block breaking portal page.
By default it is installed as a center block. When active all center blocks and footer and or right blocks do not display

**Comment by MWE001** [comment]
the fix is located here http://integramod.com/forum/viewtopic.php?f=2&t=8503 So we can close this one safely?

**Comment by MWE001** [comment]
#Bump

**Comment by vendethiel** [comment]
It seems the fix hasn't been applied yet

**Comment by MWE001** [comment]
Did this posted fix from Integra website ever get pushed and merged?

**Comment by vendethiel** [comment]
I'll try to check this week

**Comment by vendethiel** [comment]
I applicated all the fixes plus some more. I have a batch of commits ready for when I come back from holidays.

**Comment by vendethiel** [comment]
Pushed.
