### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD151#40]
Here is the million dollar question and I am sure it might not even be an issue. Are we able to upgrade to 151 from 141? or from a standard phpBB (not that there are alot of phpBB refugees beating down our doors now days). If we can upgrade, are we still having to copy phpbb_security info and install new security then copy info over like we have had to do in the past?

Also if up-gradable, template issues like we had coming to 1.4.1.

I have absolutely 0 server space to test with. My WAMP is fired up. Will it work if this is possible? 

And my apologies if I am putting the cart before the horse. That is not my intention. Just curious. :-)

**Comment by IntegraMOD** [comment]
db differences are small and easily upgradable. 141 templates should still work but I think there are differences in the login function if memory serves. I think there are only two or three sections that need updating. There may be other small issues but those can wait until 151 is viable. The problem with most 141 templates is that they are totally fixed width and poorly built. I know because I wrote most of them for 131 and 140 when I was still an html newb...lol  Im currently rebuilding fisubice and removing all images and replacing most with fontello and font awsome icons. http://integramod.net/beta/IM151/

**Comment by MWE001** [comment]
Right on sounds good. And that is great you brought up font awesome. I just built two bootstrap templates and integrated font awesome into both of them. I also used it on a fixed width site i am working on. Makes life a lot easier to add icons.

Is there any major differences between the 150 and 141? The reason I ask is I have a fella, who has a 141 site and I am patching it up daily to keep it going and the ship is sinking fast. After he got hacked today, I kindly told he we need to think about available options if he wants to remain online. And we are talking almost 1500 members he would loose. 

I'm really digging for options at this point in time. I know the version of 150 we have here on Git is working 95% better than his install of 141. The only way I can keep him in business is to roll back php to an un thinkable version or try as I might to get this version to work.  I'm stumped.

**Comment by MWE001** [comment]
Visited and got banned all at once  lol

It appears you have been banned from this website. If this is a mistake or you are not sure why you are banned, please contact the board administrator.

Board Administrator: xxxxxxx1965 [at] hotmail.com

You have been blocked because you have permission to be staff, but the admins did not grant you permission in the security panel.

**Comment by IntegraMOD** [comment]
? this is from the demo link I sent you? There are no users other than me

**Comment by MWE001** [comment]
Yeah I clicked the link and was insta banned

**Comment by IntegraMOD** [comment]
was he hacked through the forum or his server?

**Comment by MWE001** [comment]
that I am not sure. i posted privately at integra about it in a admin thread. I have the raw access log but I am not a server guy. I can read it, but it is all chinese to me. I was in scramble mode today to find out how but came up in wonder.

**Comment by MWE001** [comment]
Only his index.php was defaced and including files from somewhere. the where, i am not sure.

**Comment by IntegraMOD** [comment]
can you do a default install of IM141 and send me a zip of the db? My php is too adv to install it but I can use it to write an upgrade path

**Comment by MWE001** [comment]
Sorry chief, I got side tracked. Are you still interested in this? If so I can try and get a fresh install of 141 going, if I have a clean version of it laying around the archives anywhere. I have one that I know of that had a all languages version and a all english only version. For some strange reason, the English only directory is missing half the files. And I know for 100% certain the all languages had a bad issue but for the life of me my tired brain does not recall what that issue was.

**Comment by vendethiel** [comment]
I'd like to know if something happened :)

**Comment by MWE001** [comment]
@IntegraMOD  are you still interested in the database for 141? If so I am ready to roll. Got my WAMP reinstalled and ready to roll. PC seems to be holding out ok on the junk parts I used to fix it. lol

And I think I do still have his server log from when his site got hit. Ill dig it up and send with DB if you want me to. And I will need a clean zip of 141 if available. the one I have is junk. Missing loads of files for some strange reason.

**Comment by vendethiel** [comment]
Feel free to ping me if you want to try and upgrade.

**Comment by vendethiel** [comment]
gonna close this one for now, anyone can reopen if we end up doing a procedure
