### ISSUE TITLE
Default Database Dates

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD151#41]
Boys and gents, Zero Values will no longer work for default dates  and or times . 0000-00-00  It will stop an install cold. I am not sure of the fix right at the moment, but my dirty fix was to replace all those with 1969-10-10 Kinda of bogus but worked. I suppose just filling the 0000 with anything will suffice to. Not sure how to truly fix it. Most of the places I have gone are saying just to toss a date in there as well which is kind of stupid actually. That is just to down and dirty for a piece of software to use. 

Necessary though? I'm sure

**Comment by MWE001** [comment]
Also as far as schemas go, i am getting this as well.

An error occurred trying to update the database
Field 'cat_desc' doesn't have a default value

**Comment by MWE001** [comment]
Am I not sure that this is just a windows error on WAMP server? I know the date is real but why can't I set text to have a default value of  ' ' ? I know windows don't like it. I hope that is not it. I have no test room on my hosting package. Localhost is all I got.

**Comment by MWE001** [comment]
It was a windows thing as far as the no default text goes. I had to find in my.ini

sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

Comment it out and add sql_mode='MYSQL40'

Now that that is solved, i am all but 100% sure the No Zero date thing is legitimate.

**Comment by vendethiel** [comment]
We need to fix this...

**Comment by MWE001** [comment]
Yeah the 0 date and time thing is legit as far as mysql goes. The supported range is '1000-01-01' to '9999-12-31. I am not sure what version of MySQL set this standard but it is what it is.

As far as my other error goes that I posted here, is that a worry errror as well? I'm, not really sure it is a Windows thing or what. I did the fix and it worked ironically enough. so I would have to say if anyone has their server set  like mine was as far as the sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" goes, are they going to have the same issue?

So far i will say the master 150 here at Git is a decent copy thus far. I have been running it through its paces and minus this and the phpBb Security thing, it has been pretty much flawless thus far save a couple template issues.

**Comment by vendethiel** [comment]
It's an error we need to fix.

The issue is that the newest versions of MySQL and MariaDB are "stricter" than the older versions. So we need to fix all of those going forward.

**Comment by MWE001** [comment]
Not sure if this was worked on today but this time the install was flawless, up until I had to delete the install directory at which point in time I was banned from my own install ;-) I never even got to try to install Prill

**Comment by IntegraMOD** [comment]
try deleting any cookies and cached data for your wamp server from your browser.

**Comment by MWE001** [comment]
Yeah I gave up on it for a short bit and decided to get nostalgic and play some Call of Duty World at War. lol I'll give it a go in the morning and see if that was the issue. I'm hoping so. it was going to smooth for it to error like that.

**Comment by MWE001** [comment]
Hey guys sorry I have not go try this today yet. I do plan on trying again with all cookies and cache deleted in browser. I got busy today with a new bootstrap template for another CMS (for flight simulator) I am working on.

**Comment by MWE001** [comment]
Did we ever com e up with a easy fix for this? I am working on another CMS project of my own and I have this exact same issue as well.  I know when I installed Integra, I went in the sql and manually changed to a random 1969 date but I know that's not the easy answer.

**Comment by vendethiel** [comment]
I think we can go for `NOW()`.

**Comment by MWE001** [comment]
Yeah I can easily see that working for the default initial post. I bumped in to it one or two more times as well, but other than the initial post entry in the install schema, I don't recall what it was. I would need to go look again. 

Nice call.

**Comment by MWE001** [comment]
and is integra down? I cant get it to load. I have not been able to since I uploaded that file for you that day.

**Comment by vendethiel** [comment]
> and is integra down? I cant get it to load. I have not been able to since I uploaded that file for you that day.

Seems to work here :)

**Comment by IntegraMOD** [comment]
its back up. Cpanel/WHM updated and broke everything. Took 2 days to fix it but server seems good now

**Comment by MWE001** [comment]
Ah ok. Glad to hear all is well, sorry to hear it went south. I know how that goes.

**Comment by MWE001** [comment]
I just grabbed the 151 from your post helter. I'm going to attempt to give it a go. All I have to work on is WAMP. My host package is full.

**Comment by vendethiel** [comment]
I managed to install latest on MAMP, but it doesn't have the newest goodies.

**Comment by vendethiel** [comment]
I need to reinstall with the SQL strict mode. Or maybe someone else can report :-).

**Comment by MWE001** [comment]
Is this still a thing? If you all have the latest updated version I can give it a quick install on both my servers and see. I got Windows as well as my production Linux machine.

**Comment by vendethiel** [comment]
Please do, I’m afraid there might be some missing still,

**Comment by MWE001** [comment]
Is the copy here on Git the most recent one? If so I'll grab it and do a install tomorrow afternoon.

**Comment by vendethiel** [comment]
Yes, it should be good to go.

**Comment by MWE001** [comment]
This is 100% a Windows issue. Nix servers will give a warning which 99% of the time people shut them up anyhow by default so it is no biggie. People are basically screaming at developers to allow text in a "TEXT" field but I read it was a memory saver (??). 

So the short answer is, who is really installing this on Windows anyhow but for testing and local Dev so as to not develop on a live website? No one at all. So this error is useless to chase and should be closed. 

However, due to the people that DO use a Windows stack to develop and test on, can something be added to chmod when it detects that it is NOT nix and give them a message to say to disable strict mode on Windows servers? I'm not real sure. Just scraping the bottom of the barrel here.

**Comment by vendethiel** [comment]
I'd rather we fix the underlying issue at some point. You're right we can add a warning in the meantime, but it's because I didn't install a newer mySQL version that this isn't fixed yet.
I blame my new job for the lack of time..:)

**Comment by vendethiel** [comment]
I think it is fine now. I install IM on recent mysqls fairly often.
