### ISSUE TITLE
Mod Included with The EasyMod Install

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD151#42]
That mod that is included with the Integra download

MOD Title:		User Class
## MOD Description:	This mod will add new levels:

That has some edits in it in the groupcp.php that do not exist. I got some edits to work with easymod but this was a dead stop. This is not priority. This mod could be ditched if needs be. And is using easymod with PCP even practical? PCP is a royal PITA.

**Comment by MWE001** [comment]
I am going to jump back on this today to see if I can make it work or not. Last night my batteries were running on dead status as I was posting this. I'm recharged today.

**Comment by vendethiel** [comment]
Good! Maybe we should find some better way to manage user colors, btw. Maybe a user field, I'm not sure.

I just fixed some PCP errors, but after looking at the code, user colors are hardcoded :/

**Comment by MWE001** [comment]
And that is in this mod we are talking about here or in Integramod it self?  As far as this mod goes, I actually know nothing about it. I saw it in easymod last night and decided to have a look and I knew by the install doc it was not going to run.

**Comment by IntegraMOD** [comment]
Ill have to check this out because I dont recall including a mod with easymod. I added easymod so we could write future integramod updates as easymod mods. If you remember in the past many updates involved many hours of find/replace

**Comment by MWE001** [comment]
Well, if this mod that was included in the master from here is not needed, we can ditch it very easily. I was not real sure to be honest and in fact, it was due to the many find and replace and adds and removes that I was wondering why that mod was included. i was scratching my head in wonder. Adding a mod to Integra was not the easiest job in the world and never in my best days would I have pondered easymod for Integra :-D

Let me know either way and I will delete the mod out of my install and not spend any time on it.

**Comment by MWE001** [comment]
Safe to say this mod got dumped right and we can disregard and close this one to?

**Comment by vendethiel** [comment]
Seems like the mod is still there: https://github.com/IntegraMOD/IntegraMOD151/tree/master/IM150/admin/mods/User_Class

**Comment by vendethiel** [comment]
I agree that we can remove it.

**Comment by MWE001** [comment]
@IntegraMOD  so you think so to? Ditch the mod included to save on package space? I am certain the mod will not install anyhow.  If you think so to, we can get rid of it and close this topic.

**Comment by MWE001** [comment]
I would say ditch that mod that is included. And to be quite frank, is EasyMOD a waste of time with Integarmod due to PCP? THat is my thought. Nothing ever installed with PCP without a major overhaul first and very few people were proficient with PCP.

**Comment by vendethiel** [comment]
You're right. This mod is really useless with PCP anyway, let's remove it.

**Comment by IntegraMOD** [comment]
easymod was installed only to facilitate quick easy updates. It is unlikely there will ever be another 4 hour find/replace update for it but it was installed for that purpose and for any edited mods like Mr.DSL's mods

**Comment by MWE001** [comment]
Ah ok. And Mr DSL that is a blast from the past. Him and old Dragonsys. So the easyMOD can stay or go is what you are saying? Or we leave easyMOD and remove the modification package that is in it already?

**Comment by vendethiel** [comment]
The latter imho

**Comment by IntegraMOD** [comment]
You can do what you want with it but my opinion is to remove the included mod and leave easymod. If you get enough active users someone will find a vulnerability and it would be nice for your users to be able to download a security patch and quickly install it with EM.

**Comment by vendethiel** [comment]
I removed the mod. Will commit next week

**Comment by vendethiel** [comment]
I removed it.

**Comment by MWE001** [comment]
I was going to Agree with Integramod on this one and see that you did as well Ven. yeah the mod was good to go but easymod was cool to stay IMO. 

Sorry so dang late on this one guys.
