### ISSUE TITLE
integramod.com redirecting to forumimages.us?

### ISSUE THREAD

**Issue by vendethiel** [IntegraMOD/IntegraMOD151#49]
Not sure what's happening. :o

**Comment by MWE001** [comment]
Nice. I was just coming here to elaborate on that.

**Comment by vendethiel** [comment]
we're good :)

**Comment by IntegraMOD** [comment]
it was the .htaccess file I copied from forumimages. Forgot one url but it was only there for a few hours. Wonder if a dns server cached it?
