### ISSUE TITLE
Enhance the IM CMS

### ISSUE THREAD

**Issue by vendethiel** [IntegraMOD/IntegraMOD151#53]
Hi folks.

I'm actually wondering whether I should write this here or on the website.

What do you think are the biggest flaw right now for IM Portal?

**Comment by MWE001** [comment]
IMPortal itself or the Integramod package?

As the Integramod Package goes, that remains to be seen. I am just getting back to this all after some very bad life altering experiences this year. 

Right now I am working on IM Portal. Right off the start it has the old deprecated mysql_connect() error. This is easily fixed. I am working on it as we speak. I am literally an hour into testing so that is as far as I got.

As far as Integramod goes, I need to download the most recent package you and HelterSkelter have available and do some testing and get caught back up. I am way behind the times.

**Comment by vendethiel** [comment]
I mean IMPortal itself, not Integramod.
If you do get some fixes in, tell me :).

**Comment by MWE001** [comment]
Well all kidding aside, I think Helter brought it up once as well, everything is tables. Tables are not good as we all know or should know. We are stroking our own egos and wants and needs here. To be real and honest, if it is not mobile friendly (responsive and nice looking, not plain white withe text and links), it is a disaster waiting to happen anymore. 

As far as fixes go, I did get the connect issue working correctly. Not sure if it is right or not as my coding sucks but it works. The base package of IM Portal 1.3.0 has a css issue somewhere that Helter found once but I never did. Well, I did but failed to take notes and that was 10 + years ago. 

I have every IM Portal ready template made but once again, all tables and I am not real sure how far updated they are. I believe they are all phpBB 2.0.23 ready but I could be wrong. I do not think they were ever made IM Portal 1.3.0 friendly or not.

And IM Portal could really benefit from more layouts other than the default 2 layouts that it comes with. I do not know enough about java to update the layouts and make them work so for now I use other layouts I have that do not collapse. 

That is just to name a few things. The tables are the major deal breaker. If it could be updated and brought up to be comparable to a wordpress maybe (??) that would be marvelous, but a major load of work. My skills are not near good enough to even consider doing anything like that. My skills limit me to trouble shooting and minor fixes like I did with some plugins at Icy,

**Comment by vendethiel** [comment]
You're right, the tables part is really bad :(. It's the same mostly for the rest of the templates though, except for the work Helter already did. I'm really bad at design.

Wordpress is far too much work. Even getting something similar to Icy Phoenix CMS is too much work. If I could, I'd just integrate the CMS with IM (like from https://github.com/MightyGorgon/icy_phoenix_cms ) but the code is too close to phpBB3 by now...

**Comment by vendethiel** [comment]
Please test the new version I pushed to github (0c1cabe15e48051c265fef0f376b6460a0429b76) for PHP7 compat :)!

**Comment by MWE001** [comment]
It takes a load of time and effort to say the least. It is a team effort that is for sure. I am no pro at it to say the least. I can look at what Helter Skelter has done thus far and see but it is a real shot in the dark. 

I wonder how much I could learn by taking a look at Icy Phoenix mobile ready template.

**Comment by vendethiel** [comment]
One would first need to check if the Icy Phoenix mobile-ready templates got totally rid of tables. I am not sure it did, so better be careful. I'm not 100% sure.

**Comment by MWE001** [comment]
Yeah we are on the same page with that thought. I agree 100%

**Comment by vendethiel** [comment]
I went ahead and checked.

There are a few tables left (like in the footer). But it's mostly done nicely with `<div>`s. We could probably learn a bit from it. Obviously we can't just steal the files though.

**Comment by IntegraMOD** [comment]
I have done absolutely no web work in the last 3-4 years but at that time the general consensus was not to fear tables as a content container. Back then, the most advanced responsive templates still used limited tables as containers but not as design elements. I believe phpBB's 3.1x prosilver still made limited use of them

**Comment by MWE001** [comment]
I would love to say I have but everything they taught us in school was so old school it made tables look new school. lol I primarily just mess around on WAMP servers now just to pass the time away when I can. Ahh tables. The good old days when we could stuff anything we wanted on a page anywhere we wanted when it wasn't tabular data. Oh and an iframe too. :-D  I believe you are most likely right on Prosilver.  I do know for certain that e107 made the jump to bootstrap all responsive templates asap. There was no way they were getting left behind. Well, them and Drupal and WordPress. I sat back and watched a load of CMS systems go down in flames real fast as the mobile scene took hold. It happened in a flash in retrospect to how long it took it to get here.

**Comment by vendethiel** [comment]
OK, like I wrote on the forums, this is implemented now.

I just made it template-wise, every template file for the portal has a corresponding "admin/blocks_layout_page_[filename]" that's used in the admin.

I'll commit it soon. The code is not super pretty, but it works.
I removed my weird template system thing, and I'm back to using phpBB's template system, which is the only sane choice.

**Comment by vendethiel** [comment]
ecc60e92cce3f474920d722cf8bb9b65c1eea948
