### ISSUE TITLE
Poll Block Error

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/IntegraMOD151#61]
My poll forum is set to 4. Double checked IM Portal config to Poll Id set to 4, cleared cache and this happens across all my browsers. This is after creating a post and submitting. Then I figured I would try and vote and see if it would update it and no dice. 

I'm more than sure it is a quick fix. I just haven't looked at it yet. I'm dashing around checking out other stuff that isn't working too and taking down notes.

![poll chrome](https://user-images.githubusercontent.com/2566493/49524988-676da800-f872-11e8-9c02-50ec813fe3da.jpg)

**Comment by vendethiel** [comment]
I discovered a few bugs in IM with PHP7+, so I'm fixing them first, before looking into the poll block specifically.

Also I want to code a "template-like view of blocks", kind of like with Icy Phoenix's system, where the Blocks List displays what it will look like (simulating the columns etc).
I will probably have to add a file per layout, where the block positions are mapped. Or maybe in the database, who knows.

**Comment by vendethiel** [comment]
OK I fixed it. It is weird.

In the templates file for the poll block, the variables all start with a `B_`. But the block php file doesn't use that prefix, so it didn't work. Just removing the prefix fixed it.

**Comment by MWE001** [comment]
Nice! I am not real sure about the blocks at all. I never messed with them at all. I did a batch of AMOD blocks once and they went like hot cakes amongst the users but that was my dabble in the world of blocks. Oh them and a Shoutcast Block. 

Hey speaking of blocks.... Well, yes and no, that calendar, Helter has a couple Demos and the mini calendars work  on Integramod 141 and 150 both ( the forward and backward arrows). Somewhere along the lines of a commit the system was broken. When he upgraded to the version of 150 that we are fiddling with now, it broke and no longer worked. Well the entire site no longer worked but at least we got to see the mini calendars work in both prior versions.

**Comment by vendethiel** [comment]
OK, that's good to know, I'll try to pinpoint what we broke then.

**Comment by vendethiel** [comment]
I fixed the case when we already voted. Now to fix the case when we can vote...

**Comment by vendethiel** [comment]
Fixed in 9378dd7, along with quite a bit of stuff

**Comment by vendethiel** [comment]
Please confirm & fix if it works again.
