### ISSUE TITLE
Check PHP7.3 compatibility

### ISSUE THREAD

**Issue by vendethiel** [IntegraMOD/IntegraMOD151#67]
The new PHP version just dropped, we need to check if we’re working fine on that platform.

**Comment by MWE001** [comment]
I can not test up to 7.3 just yet. I might be able to if I can figure out how to upgrade php on my windows stack (WAMP Server). As of now it only goes up to 7.2.4 and my live host is only up to 7.0 thus far.

**Comment by vendethiel** [comment]
Apparently PHP7.3 is not installed on new servers because it crashes itself often lol... I'll reopen this later when php itself becomes stable.
